### ISSUE TITLE
Import Error when trying to use set up a custom manager

### ISSUE THREAD

**Issue by sampeka** [justquick/django-activity-stream#248]
I've written a custom manager, but can't use it due to an import error in `settings.py`. The error is:

`ImportError: Cannot import social.managers.MyActionManager try fixing ACTSTREAM_SETTINGS[MANAGER]setting.`

These are the settings:

    ACTSTREAM_SETTINGS = {
        'MANAGER': 'social.managers.MyActionManager',
        'FETCH_RELATIONS': True,
        'USE_JSONFIELD': True
    }

And this is the `social.managers` file:

    from datetime import datetime, timedelta

    from actstream.managers import ActionManager, stream
    from actstream.models import following, user_stream

    class MyActionManager(ActionManager):

        @stream
        def any_followed_stream(self, user, **kwargs):
            date_start = datetime.now() - timedelta(days=3)
            return user_stream(user).filter(date__gte=date_start)

The path is definitely correctly, so not sure what's wrong here?

**Comment by justquick** [comment]
the import error catch might be silencing the underlying traceback. can you please try to patch actstream/settings.py to raise the original error like this?

```diff
diff --git a/actstream/settings.py b/actstream/settings.py
index 65e7ca5..a69a089 100644
--- a/actstream/settings.py
+++ b/actstream/settings.py
@@ -14,6 +14,7 @@ def get_action_manager():
         return getattr(__import__('.'.join(mod_path[:-1]), {}, {},
                                   [mod_path[-1]]), mod_path[-1])()
     except ImportError:
+        raise
         raise ImportError('Cannot import %s try fixing ACTSTREAM_SETTINGS[MANAGER]'
                           'setting.' % mod)
```

**Comment by sampeka** [comment]
Traceback:

```
Traceback (most recent call last):
  File "/Users/sampeka/dev/thestylelocker2/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/sampeka/virtualenv/thestylelocker/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/sampeka/virtualenv/thestylelocker/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/sampeka/virtualenv/thestylelocker/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/sampeka/virtualenv/thestylelocker/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/sampeka/virtualenv/thestylelocker/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/sampeka/dev/django-activity-stream/actstream/models.py", line 47, in <module>
    class Action(models.Model):
  File "/Users/sampeka/dev/django-activity-stream/actstream/models.py", line 100, in Action
    objects = actstream_settings.get_action_manager()
  File "/Users/sampeka/dev/django-activity-stream/actstream/settings.py", line 15, in get_action_manager
    [mod_path[-1]]), mod_path[-1])()
  File "/Users/sampeka/dev/thestylelocker2/social/managers.py", line 4, in <module>
    from actstream.models import following, user_stream
ImportError: cannot import name 'following'
```

**Comment by justquick** [comment]
it looks like your hitting a cyclical import error when importing from `actstream.models` in your manager. try moving the import statements into the stream methods like so

```python
from datetime import datetime, timedelta

from actstream.managers import ActionManager, stream

class MyActionManager(ActionManager):

    @stream
    def any_followed_stream(self, user, **kwargs):
        from actstream.models import user_stream
        date_start = datetime.now() - timedelta(days=3)
        return user_stream(user).filter(date__gte=date_start)
```

**Comment by sampeka** [comment]
That fixed it, thanks a lot!

**Comment by silasseB** [comment]
Im having the same problem, Would anyone helo me?
