### ISSUE TITLE
Follow not working

### ISSUE THREAD

**Issue by jaineshp** [justquick/django-activity-stream#249]
>>>y=User.objects.get(id=1)
    >>>z=User.objects.get(id=2)
    >>>follow(y,z)
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/actstream/actions.py", line 45, in follow
        action.send(user, verb=_('started following'), target=obj, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 201, in send
        response = receiver(signal=self, sender=sender, **named)
      File "/usr/local/lib/python2.7/dist-packages/actstream/actions.py", line 116, in action_handler
        newaction.save(force_insert=True)
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 710, in save
        force_update=force_update, update_fields=update_fields)
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 738, in save_base
        updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 822, in _save_table
        result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 861, in _do_insert
        using=using, raw=raw)
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in     manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 920, in _insert
        return query.get_compiler(using=using).execute_sql(return_id)
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
        cursor.execute(sql, params)
      File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
        return super(CursorDebugWrapper, self).execute(sql, params)
      File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
      File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
      File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in     execute
        return Database.Cursor.execute(self, query, params)
    OperationalError: table actstream_action has no column named data

And then when again just after this

    >>> follow(y,z)
    <Follow: jp -> lol>
    >>> 
What to do in here?

**Comment by jaineshp** [comment]
Silly mistake. I forgot to python manage.py makemigrations
