### ISSUE TITLE
Django 1.9rc2, can't use actstream in INSTALLED_APPS

### ISSUE THREAD

**Issue by jbsag** [justquick/django-activity-stream#270]
Steps to repeat

``$ pip install Django==1.9rc2 django-activity-stream``

``$ django-admin startproject hello_world``

Add ``actstream`` to ``INSTALLED_APPS``.

``$ ./manage.py shell``

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/anon/.virtualenvs/tmp-2bf0b02c5af0bd9/lib/python3.5/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/Users/anon/.virtualenvs/tmp-2bf0b02c5af0bd9/lib/python3.5/site-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/Users/anon/.virtualenvs/tmp-2bf0b02c5af0bd9/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/anon/.virtualenvs/tmp-2bf0b02c5af0bd9/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/anon/.virtualenvs/tmp-2bf0b02c5af0bd9/lib/python3.5/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/Users/anon/.virtualenvs/tmp-2bf0b02c5af0bd9/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/anon/.virtualenvs/tmp-2bf0b02c5af0bd9/lib/python3.5/site-packages/actstream/apps.py", line 6, in <module>
    from actstream.actions import action_handler
  File "/Users/anon/.virtualenvs/tmp-2bf0b02c5af0bd9/lib/python3.5/site-packages/actstream/actions.py", line 5, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/Users/anon/.virtualenvs/tmp-2bf0b02c5af0bd9/lib/python3.5/site-packages/django/contrib/contenttypes/models.py", line 159, in <module>
    class ContentType(models.Model):
  File "/Users/anon/.virtualenvs/tmp-2bf0b02c5af0bd9/lib/python3.5/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/Users/anon/.virtualenvs/tmp-2bf0b02c5af0bd9/lib/python3.5/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/Users/anon/.virtualenvs/tmp-2bf0b02c5af0bd9/lib/python3.5/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.`
```

**Comment by g3rd** [comment]
I'm seeing the same error with Django == 1.9

**Comment by jbsag** [comment]
Yep, this also happens in 1.9. 
The error appears to be introduced through this commit: https://github.com/django/django/commit/9033003d97d29f7754b0840333f6f362c0cd31f7

Here's the same steps, except with `$ pip install django`, and I ran `$ ./manage.py ` by itself.

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/anon/.virtualenvs/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/Users/anon/.virtualenvs/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/Users/anon/.virtualenvs/venv/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/anon/.virtualenvs/venv/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/anon/.virtualenvs/venv/lib/python3.5/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/Users/anon/.virtualenvs/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/anon/.virtualenvs/venv/lib/python3.5/site-packages/actstream/apps.py", line 6, in <module>
    from actstream.actions import action_handler
  File "/Users/anon/.virtualenvs/venv/lib/python3.5/site-packages/actstream/actions.py", line 5, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/Users/anon/.virtualenvs/venv/lib/python3.5/site-packages/django/contrib/contenttypes/models.py", line 159, in <module>
    class ContentType(models.Model):
  File "/Users/anon/.virtualenvs/venv/lib/python3.5/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/Users/anon/.virtualenvs/venv/lib/python3.5/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/Users/anon/.virtualenvs/venv/lib/python3.5/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by g3rd** [comment]
Fix #270 works in a test app I created. I was working my way through parts of the app but you beat me to it.
Thanks @jbsag!

**Comment by anjos** [comment]
Any plans to see this applied upstream and a pypi release?

**Comment by cjerdonek** [comment]
:+1: for Django 1.9 compatibility. Thanks for a great project!

**Comment by meizon** [comment]
It would be great if this could be merged.

**Comment by gratimax** [comment]
:+1: would also like to see this

**Comment by NogerbekNurzhan** [comment]
Hello guys! Is it possible to use this app with Django 1.10? I am little bit comfused cause I have the same error. Can someone give me advice?

**Comment by auvipy** [comment]
you could install from master
