### ISSUE TITLE
Unable to register models on django 1.9

### ISSUE THREAD

**Issue by larubbio** [justquick/django-activity-stream#274]
The example in the documentation throws the following exception in django 1.9:

```
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/rob/code/abett.api/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/Users/rob/code/abett.api/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/rob/code/abett.api/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 176, in fetch_command
    commands = get_commands()
  File "/Users/rob/code/abett.api/env/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/rob/code/abett.api/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 71, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "/Users/rob/code/abett.api/env/lib/python2.7/site-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/Users/rob/code/abett.api/env/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

I get this exception if I try to use the <1.7 example from the docs:

```
Traceback (most recent call last):
  File "/Users/rob/code/abett.api/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/rob/code/abett.api/env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/rob/code/abett.api/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/rob/code/abett.api/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/rob/code/abett.api/env/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/rob/code/abett.api/env/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/rob/code/abett.api/env/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/rob/code/abett.api/abett/api/models.py", line 9, in <module>
    registry.register('Friendship')
  File "/Users/rob/code/django-activity-stream/actstream/registry.py", line 93, in register
    model_class = validate(class_or_label)
  File "/Users/rob/code/django-activity-stream/actstream/registry.py", line 73, in validate
    model_class = get_model(*model_class.split('.'))
  File "/Users/rob/code/abett.api/env/lib/python2.7/site-packages/django/apps/registry.py", line 194, in get_model
    self.check_models_ready()
  File "/Users/rob/code/abett.api/env/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```

**Comment by larubbio** [comment]
Looking at the changes in 1.9 I see this:

https://docs.djangoproject.com/en/1.9/releases/1.9/

```
All models need to be defined inside an installed application or declare an explicit app_label. Furthermore, it isn’t possible to import them before their application is loaded. In particular, it isn’t possible to import models inside the root package of an application.
```

When I add `from actstream import registry` in my apps.py I get the stacktraces above.

**Comment by maxicecilia** [comment]
I'm having the same problem with Django==1.9 and django-activity-stream==0.6.0
Looks like the problem is between these lines
```
# actstream/apps.py
from actstream.actions import action_handler
from actstream.compat import AppConfig
```

**Comment by techdragon** [comment]
I worked around this by moving `from actstream import registry` inside the ready function.

**Comment by maxicecilia** [comment]
@techdragon What Django version are you using?

**Comment by techdragon** [comment]
1.9

**Comment by larubbio** [comment]
I still get the same error with 1.9.2 even if I move the import into the ready function.

**Comment by maxicecilia** [comment]
me too

**Comment by jbsag** [comment]
This was fixed in #270. A release just hasn't been pushed to PyPI as of yet. I'm currently installing off of a commit in the master branch for the time being.

**Comment by larubbio** [comment]
ok, I thought #272 was just about warnings on startup like the new url format.  I think this can be closed as a dupe then.

**Comment by seanauriti** [comment]
Was getting the same error moving ` import actstream import registry` along with some other imports inside the ready function worked.
