### ISSUE TITLE
Django 1.10 removes django.conf.urls.patterns (deprecated in 1.8)

### ISSUE THREAD

**Issue by awatts** [justquick/django-activity-stream#308]
urls.py starts with:

``` python
try:                                                                               
    from django.conf.urls import url, patterns                                     
except ImportError:                                                                
    from django.conf.urls.defaults import url, patterns                                                                                      
```

`django.conf.urls.patterns` is removed in Django 1.10, so the exception handler tries to use the even older `django.conf.urls.defaults`, leading to an `ImportError` on Django 1.10. Changing to 

``` python
try:                                                                               
    from django.conf.urls import url                                    
except ImportError:                                                                
    from django.conf.urls.defaults import url, patterns
```

works in 1.10, but could cause problems on < 1.8.

Maybe change at the bottom of urls.py from:

``` python
if django.VERSION[:2] < (1, 9):                                                    
    urlpatterns = patterns('', *urlpatterns)
```

to

``` python
if django.VERSION[:2] < (1, 9):       
    try:
        from django.conf.urls import patterns
    except ImportError:
        from django.conf.urls.defaults import patterns                                         
    urlpatterns = patterns('', *urlpatterns)
```

**Comment by anjos** [comment]
Maybe making this a PR will help developers to quickly integrate it?

**Comment by awatts** [comment]
Done: #311

**Comment by rmishra7** [comment]
for django 1.10 as of now until new release come, i have created custom urls.py file for actstream and pointed all the urls to actstream feeds and views. i know its very silly thing to tell but just in case we can do a temporary solution.

**Comment by auvipy** [comment]
fixed in master

**Comment by NogerbekNurzhan** [comment]
Also I has this error when try ti migrate after setup app:

```
Failed to get real commands on module "RMS": python process died with code 1: Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.1.2\helpers\pycharm\_jb_manage_tasks_provider.py", line 25, in <module>
    django.setup()
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\apps\config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Nurzhan\PycharmProjects\RMS\project\models.py", line 95, in <module>
    registry.register(UserCharacteristic)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\actstream\registry.py", line 95, in register
    self[model_class] = setup_generic_relations(model_class)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\actstream\registry.py", line 22, in setup_generic_relations
    Action = get_model('actstream', 'action')
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\apps\registry.py", line 192, in get_model
    self.check_models_ready()
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\apps\registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```
