### ISSUE TITLE
How create activity list for connected modals?

### ISSUE THREAD

**Issue by NogerbekNurzhan** [justquick/django-activity-stream#344]
Hello! I have one question. Is it possible to create next thing with the help of this app? I was really confused after reading the documentation. Pls help!

I have model `Project`. Also I have models as `Characterictic` and `Task` which are related with Project. In other words every project has sections like Characterictic and Task. Users can add comment to any characterictic or task objects.

I want to show in template last 10 activity which was in current project. Order that list by time. As you can see from the modals every Characterictic and Task has fields like: revision_date (Last time of update) and creation_date (Date of creation). Also Comment model has field created which show when comment was created.

**For example**:
```
Project A:
1) User A added comment to Task A in  11:45
2) User B edited Characterictic B  in 11:30.
3) User B added comment to Characterictic C in 10:30.
***
10) User B created Characterictic A in 09:00.

Project B:
1) User A added comment to Task A in  11:45
2) User B edited Characterictic B  in 11:30.
3) User B added comment to Characterictic C in 10:30.
***
10) User B created Characterictic A in 09:00.
```

**models.py:**
```
class Project(models.Model):
    name = models.CharField(_('Name'), max_length=250)
    create_time = models.DateTimeField(auto_now_add=True)
    revision_date = models.DateTimeField(_('Date of last update'), auto_now=True)

class Characteristic(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    symbol = models.CharField(_('Symbol'), max_length=250)
    description = models.TextField(_('Description'))
    comments = models.ManyToManyField("Comment")
    create_time = models.DateTimeField(auto_now_add=True)
    revision_date = models.DateTimeField(_('Date of last update'), auto_now=True)

class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    symbol = models.CharField(_('Symbol'), max_length=250)
    description = models.TextField(_('Description'))
    comments = models.ManyToManyField("Comment")
    create_time = models.DateTimeField(auto_now_add=True)
    revision_date = models.DateTimeField(_('Date of last update'), auto_now=True)

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
```

**Comment by auvipy** [comment]
yes this feature is possible using this pack.

**Comment by NogerbekNurzhan** [comment]
@auvipy Hello! I am really comfused after reading the docs. PLS can you show me just simple example by one model? Lets say to Characteristic modal.

**Example**:
```
1) User A add comment to Characterictic B in 11:45
2) User B edit Characterictic C in 11:00
3) User C create Characterictic А in 09:55.
```

**Comment by auvipy** [comment]
read the docs thoroughly

**Comment by NogerbekNurzhan** [comment]
It is too unclear from docs to understand the steps what you need to do =(

First I register modal as:

```
from actstream import registry

class Characterictic(models.Model):
    ...

registry.register(Characterictic)
```

But dont understand what I need to do next.

**Comment by NogerbekNurzhan** [comment]
Also I has this error when try to migrate:

```
Failed to get real commands on module "RMS": python process died with code 1: Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.1.2\helpers\pycharm\_jb_manage_tasks_provider.py", line 25, in <module>
    django.setup()
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\apps\config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Nurzhan\PycharmProjects\RMS\project\models.py", line 95, in <module>
    registry.register(UserCharacteristic)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\actstream\registry.py", line 95, in register
    self[model_class] = setup_generic_relations(model_class)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\actstream\registry.py", line 22, in setup_generic_relations
    Action = get_model('actstream', 'action')
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\apps\registry.py", line 192, in get_model
    self.check_models_ready()
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\apps\registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```

**Comment by NogerbekNurzhan** [comment]
Is this app works with Django 1.10?

**Comment by NogerbekNurzhan** [comment]
I have this error when try to migrate:

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.1.2\helpers\pycharm\django_manage.py", line 43, in <module>
    run_module(manage_file, None, '__main__', True)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 196, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:/Users/Nurzhan/PycharmProjects/RMS\manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\management\__init__.py", line 341, in execute
    django.setup()
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\apps\config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:/Users/Nurzhan/PycharmProjects/RMS\project\models.py", line 95, in <module>
    registry.register(UserCharacteristic)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\actstream\registry.py", line 95, in register
    self[model_class] = setup_generic_relations(model_class)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\actstream\registry.py", line 22, in setup_generic_relations
    Action = get_model('actstream', 'action')
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\apps\registry.py", line 192, in get_model
    self.check_models_ready()
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\apps\registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```

**Comment by auvipy** [comment]
follow the docs

**Comment by NogerbekNurzhan** [comment]
@auvipy It seems like app dont work with Django 1.10. Its sad. I found that a lot of people has this error.
