### ISSUE TITLE
django import missing

### ISSUE THREAD

**Issue by luiscastillocr** [justquick/django-activity-stream#370]
I think there is a missing import in https://github.com/justquick/django-activity-stream/blob/master/actstream/registry.py

`
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/var/lib/jenkins/workspace/wikirealty/lib/python3.4/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/jenkins/workspace/wikirealty/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/var/lib/jenkins/workspace/wikirealty/lib/python3.4/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/lib/jenkins/workspace/wikirealty/lib/python3.4/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/var/lib/jenkins/workspace/wikirealty-staging-api/apps/activity_feed/apps.py", line 13, in ready
    registry.register(User)
  File "/var/lib/jenkins/workspace/wikirealty/lib/python3.4/site-packages/actstream/registry.py", line 90, in register
    self[model_class] = setup_generic_relations(model_class)
  File "/var/lib/jenkins/workspace/wikirealty/lib/python3.4/site-packages/actstream/registry.py", line 30, in setup_generic_relations
    if django.VERSION[:2] >= (1, 8):
NameError: name 'django' is not defined
`
0.6.5 seems to be okay though

**Comment by auvipy** [comment]
yes master is broken

**Comment by auvipy** [comment]
it should be fixed now
