### ISSUE TITLE
Django 2.1 incompatibility ?

### ISSUE THREAD

**Issue by Agi-dev** [justquick/django-activity-stream#402]
Hi,

I've upgraded my django version to 2.1 and I've got this message when I launch 'python manage.py' :

`
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/francois/.local/share/virtualenvs/tao-back-54Rbleea/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/francois/.local/share/virtualenvs/tao-back-54Rbleea/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/Users/francois/.local/share/virtualenvs/tao-back-54Rbleea/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/francois/.local/share/virtualenvs/tao-back-54Rbleea/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/Users/francois/.local/share/virtualenvs/tao-back-54Rbleea/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/francois/.local/share/virtualenvs/tao-back-54Rbleea/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/francois/.local/share/virtualenvs/tao-back-54Rbleea/lib/python3.6/site-packages/actstream/models.py", line 57, in <module>
    class Action(models.Model):
  File "/Users/francois/.local/share/virtualenvs/tao-back-54Rbleea/lib/python3.6/site-packages/actstream/models.py", line 171, in Action
    @models.permalink
AttributeError: module 'django.db.models' has no attribute 'permalink'
`

When I downgrade to Django <2.1, it's working.

**Comment by auvipy** [comment]
yes the pypi version do not support 2.0 and 2.1 fully but the master does. it will be great if you try the master branch with django 2.1 and report if anything doesn't work

**Comment by Agi-dev** [comment]
I've tried with master branch and Django 2.1. 
All my pytests succeed !

**Comment by auvipy** [comment]
thanks!
